/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_PERCENT_DASH_DASH = 1,
  anon_sym_DASH_DASH_PERCENT_GT = 2,
  anon_sym_LT_PERCENT_AT = 3,
  anon_sym_PERCENT_GT = 4,
  aux_sym_directive_attribute_token1 = 5,
  aux_sym_directive_attribute_token2 = 6,
  anon_sym_LT_PERCENT_BANG = 7,
  anon_sym_LT_PERCENT_EQ = 8,
  anon_sym_LT_PERCENT = 9,
  anon_sym_DOLLAR_LBRACE = 10,
  anon_sym_POUND_LBRACE = 11,
  anon_sym_RBRACE = 12,
  aux_sym_el_content_token1 = 13,
  aux_sym_el_content_token2 = 14,
  anon_sym_SQUOTE = 15,
  aux_sym_el_content_token3 = 16,
  anon_sym_BSLASH = 17,
  aux_sym_el_content_token4 = 18,
  aux_sym_content_token1 = 19,
  aux_sym_content_token2 = 20,
  aux_sym_content_token3 = 21,
  anon_sym_DOLLAR = 22,
  anon_sym_POUND = 23,
  anon_sym_LT = 24,
  sym__comment_content = 25,
  sym_template = 26,
  sym_comment = 27,
  sym_directive = 28,
  sym_directive_attribute = 29,
  sym_declaration = 30,
  sym_expression = 31,
  sym_scriptlet = 32,
  sym_code = 33,
  sym_el_expression = 34,
  sym_el_content = 35,
  sym_content = 36,
  aux_sym_template_repeat1 = 37,
  aux_sym_directive_attribute_repeat1 = 38,
  aux_sym_el_content_repeat1 = 39,
  aux_sym_content_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_PERCENT_DASH_DASH] = "<%--",
  [anon_sym_DASH_DASH_PERCENT_GT] = "--%>",
  [anon_sym_LT_PERCENT_AT] = "<%@",
  [anon_sym_PERCENT_GT] = "%>",
  [aux_sym_directive_attribute_token1] = "directive_attribute_token1",
  [aux_sym_directive_attribute_token2] = "directive_attribute_token2",
  [anon_sym_LT_PERCENT_BANG] = "<%!",
  [anon_sym_LT_PERCENT_EQ] = "<%=",
  [anon_sym_LT_PERCENT] = "<%",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_POUND_LBRACE] = "#{",
  [anon_sym_RBRACE] = "}",
  [aux_sym_el_content_token1] = "el_content_token1",
  [aux_sym_el_content_token2] = "el_content_token2",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_el_content_token3] = "el_content_token3",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_el_content_token4] = "el_content_token4",
  [aux_sym_content_token1] = "content_token1",
  [aux_sym_content_token2] = "content_token2",
  [aux_sym_content_token3] = "content_token3",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_POUND] = "#",
  [anon_sym_LT] = "<",
  [sym__comment_content] = "_comment_content",
  [sym_template] = "template",
  [sym_comment] = "comment",
  [sym_directive] = "directive",
  [sym_directive_attribute] = "directive_attribute",
  [sym_declaration] = "declaration",
  [sym_expression] = "expression",
  [sym_scriptlet] = "scriptlet",
  [sym_code] = "code",
  [sym_el_expression] = "el_expression",
  [sym_el_content] = "el_content",
  [sym_content] = "content",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_directive_attribute_repeat1] = "directive_attribute_repeat1",
  [aux_sym_el_content_repeat1] = "el_content_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_PERCENT_DASH_DASH] = anon_sym_LT_PERCENT_DASH_DASH,
  [anon_sym_DASH_DASH_PERCENT_GT] = anon_sym_DASH_DASH_PERCENT_GT,
  [anon_sym_LT_PERCENT_AT] = anon_sym_LT_PERCENT_AT,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [aux_sym_directive_attribute_token1] = aux_sym_directive_attribute_token1,
  [aux_sym_directive_attribute_token2] = aux_sym_directive_attribute_token2,
  [anon_sym_LT_PERCENT_BANG] = anon_sym_LT_PERCENT_BANG,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_el_content_token1] = aux_sym_el_content_token1,
  [aux_sym_el_content_token2] = aux_sym_el_content_token2,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_el_content_token3] = aux_sym_el_content_token3,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_el_content_token4] = aux_sym_el_content_token4,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [aux_sym_content_token2] = aux_sym_content_token2,
  [aux_sym_content_token3] = aux_sym_content_token3,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LT] = anon_sym_LT,
  [sym__comment_content] = sym__comment_content,
  [sym_template] = sym_template,
  [sym_comment] = sym_comment,
  [sym_directive] = sym_directive,
  [sym_directive_attribute] = sym_directive_attribute,
  [sym_declaration] = sym_declaration,
  [sym_expression] = sym_expression,
  [sym_scriptlet] = sym_scriptlet,
  [sym_code] = sym_code,
  [sym_el_expression] = sym_el_expression,
  [sym_el_content] = sym_el_content,
  [sym_content] = sym_content,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_directive_attribute_repeat1] = aux_sym_directive_attribute_repeat1,
  [aux_sym_el_content_repeat1] = aux_sym_el_content_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_attribute_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_attribute_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_PERCENT_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_el_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_el_content_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_el_content_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_el_content_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym__comment_content] = {
    .visible = false,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_scriptlet] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_el_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_el_content] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_attribute_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_el_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '#', 38,
        '$', 37,
        '%', 33,
        '\'', 27,
        '-', 32,
        '<', 39,
        '\\', 30,
        '}', 24,
      );
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(7);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(16);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '$') ADVANCE(37);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH_DASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_PERCENT_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_AT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_directive_attribute_token1);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_directive_attribute_token2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_BANG);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '=') ADVANCE(20);
      if (lookahead == '@') ADVANCE(15);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_el_content_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '}') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_el_content_token2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_el_content_token3);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_el_content_token4);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_el_content_token4);
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_el_content_token4);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '<') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_content_token2);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_content_token3);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '%') ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3, .external_lex_state = 1},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 28},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 28},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_AT] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [aux_sym_directive_attribute_token2] = ACTIONS(1),
    [anon_sym_LT_PERCENT_BANG] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_el_content_token2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_el_content_token4] = ACTIONS(1),
    [aux_sym_content_token2] = ACTIONS(1),
    [aux_sym_content_token3] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym__comment_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(36),
    [sym_comment] = STATE(2),
    [sym_directive] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_expression] = STATE(2),
    [sym_scriptlet] = STATE(2),
    [sym_el_expression] = STATE(2),
    [sym_content] = STATE(2),
    [aux_sym_template_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_PERCENT_DASH_DASH] = ACTIONS(5),
    [anon_sym_LT_PERCENT_AT] = ACTIONS(7),
    [anon_sym_LT_PERCENT_BANG] = ACTIONS(9),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(11),
    [anon_sym_LT_PERCENT] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_POUND_LBRACE] = ACTIONS(15),
    [aux_sym_content_token1] = ACTIONS(17),
    [aux_sym_content_token2] = ACTIONS(17),
    [aux_sym_content_token3] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [anon_sym_POUND] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym_comment] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_declaration] = STATE(3),
    [sym_expression] = STATE(3),
    [sym_scriptlet] = STATE(3),
    [sym_el_expression] = STATE(3),
    [sym_content] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LT_PERCENT_DASH_DASH] = ACTIONS(5),
    [anon_sym_LT_PERCENT_AT] = ACTIONS(7),
    [anon_sym_LT_PERCENT_BANG] = ACTIONS(9),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(11),
    [anon_sym_LT_PERCENT] = ACTIONS(13),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(15),
    [anon_sym_POUND_LBRACE] = ACTIONS(15),
    [aux_sym_content_token1] = ACTIONS(17),
    [aux_sym_content_token2] = ACTIONS(17),
    [aux_sym_content_token3] = ACTIONS(17),
    [anon_sym_DOLLAR] = ACTIONS(19),
    [anon_sym_POUND] = ACTIONS(19),
    [anon_sym_LT] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_comment] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_declaration] = STATE(3),
    [sym_expression] = STATE(3),
    [sym_scriptlet] = STATE(3),
    [sym_el_expression] = STATE(3),
    [sym_content] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LT_PERCENT_DASH_DASH] = ACTIONS(25),
    [anon_sym_LT_PERCENT_AT] = ACTIONS(28),
    [anon_sym_LT_PERCENT_BANG] = ACTIONS(31),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(34),
    [anon_sym_LT_PERCENT] = ACTIONS(37),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(40),
    [anon_sym_POUND_LBRACE] = ACTIONS(40),
    [aux_sym_content_token1] = ACTIONS(43),
    [aux_sym_content_token2] = ACTIONS(43),
    [aux_sym_content_token3] = ACTIONS(43),
    [anon_sym_DOLLAR] = ACTIONS(46),
    [anon_sym_POUND] = ACTIONS(46),
    [anon_sym_LT] = ACTIONS(46),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(51), 1,
      anon_sym_LT_PERCENT,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(53), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
    ACTIONS(55), 3,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
  [26] = 5,
    ACTIONS(59), 1,
      anon_sym_LT_PERCENT,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(61), 3,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
    ACTIONS(64), 3,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
  [52] = 2,
    ACTIONS(69), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(67), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [71] = 2,
    ACTIONS(73), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(71), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [90] = 2,
    ACTIONS(77), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(75), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [109] = 2,
    ACTIONS(81), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [128] = 2,
    ACTIONS(85), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [147] = 2,
    ACTIONS(89), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [166] = 2,
    ACTIONS(93), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(91), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [185] = 2,
    ACTIONS(97), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(95), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [204] = 2,
    ACTIONS(101), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(99), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [223] = 2,
    ACTIONS(105), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(103), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [242] = 2,
    ACTIONS(109), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(107), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [261] = 2,
    ACTIONS(113), 4,
      anon_sym_LT_PERCENT,
      anon_sym_DOLLAR,
      anon_sym_POUND,
      anon_sym_LT,
    ACTIONS(111), 10,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_DASH_DASH,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_BANG,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_POUND_LBRACE,
      aux_sym_content_token1,
      aux_sym_content_token2,
      aux_sym_content_token3,
  [280] = 5,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      anon_sym_SQUOTE,
    STATE(24), 1,
      aux_sym_el_content_repeat1,
    STATE(34), 1,
      sym_el_content,
    ACTIONS(117), 2,
      aux_sym_el_content_token1,
      aux_sym_el_content_token2,
  [297] = 4,
    ACTIONS(121), 1,
      anon_sym_PERCENT_GT,
    STATE(25), 1,
      aux_sym_directive_attribute_repeat1,
    STATE(37), 1,
      sym_directive_attribute,
    ACTIONS(123), 2,
      aux_sym_directive_attribute_token1,
      aux_sym_directive_attribute_token2,
  [311] = 4,
    ACTIONS(125), 1,
      anon_sym_PERCENT_GT,
    STATE(26), 1,
      aux_sym_directive_attribute_repeat1,
    STATE(38), 1,
      sym_code,
    ACTIONS(127), 2,
      aux_sym_directive_attribute_token1,
      aux_sym_directive_attribute_token2,
  [325] = 4,
    ACTIONS(129), 1,
      anon_sym_PERCENT_GT,
    STATE(26), 1,
      aux_sym_directive_attribute_repeat1,
    STATE(35), 1,
      sym_code,
    ACTIONS(127), 2,
      aux_sym_directive_attribute_token1,
      aux_sym_directive_attribute_token2,
  [339] = 4,
    ACTIONS(131), 1,
      anon_sym_PERCENT_GT,
    STATE(26), 1,
      aux_sym_directive_attribute_repeat1,
    STATE(32), 1,
      sym_code,
    ACTIONS(127), 2,
      aux_sym_directive_attribute_token1,
      aux_sym_directive_attribute_token2,
  [353] = 4,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(138), 1,
      anon_sym_SQUOTE,
    STATE(23), 1,
      aux_sym_el_content_repeat1,
    ACTIONS(135), 2,
      aux_sym_el_content_token1,
      aux_sym_el_content_token2,
  [367] = 4,
    ACTIONS(119), 1,
      anon_sym_SQUOTE,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_el_content_repeat1,
    ACTIONS(143), 2,
      aux_sym_el_content_token1,
      aux_sym_el_content_token2,
  [381] = 3,
    ACTIONS(145), 1,
      anon_sym_PERCENT_GT,
    STATE(27), 1,
      aux_sym_directive_attribute_repeat1,
    ACTIONS(147), 2,
      aux_sym_directive_attribute_token1,
      aux_sym_directive_attribute_token2,
  [392] = 3,
    ACTIONS(149), 1,
      anon_sym_PERCENT_GT,
    STATE(27), 1,
      aux_sym_directive_attribute_repeat1,
    ACTIONS(147), 2,
      aux_sym_directive_attribute_token1,
      aux_sym_directive_attribute_token2,
  [403] = 3,
    ACTIONS(151), 1,
      anon_sym_PERCENT_GT,
    STATE(27), 1,
      aux_sym_directive_attribute_repeat1,
    ACTIONS(153), 2,
      aux_sym_directive_attribute_token1,
      aux_sym_directive_attribute_token2,
  [414] = 1,
    ACTIONS(156), 4,
      anon_sym_RBRACE,
      aux_sym_el_content_token1,
      aux_sym_el_content_token2,
      anon_sym_SQUOTE,
  [421] = 1,
    ACTIONS(158), 4,
      anon_sym_RBRACE,
      aux_sym_el_content_token1,
      aux_sym_el_content_token2,
      anon_sym_SQUOTE,
  [428] = 2,
    ACTIONS(160), 1,
      anon_sym_SQUOTE,
    ACTIONS(162), 1,
      anon_sym_BSLASH,
  [435] = 2,
    ACTIONS(164), 1,
      anon_sym_DASH_DASH_PERCENT_GT,
    ACTIONS(166), 1,
      sym__comment_content,
  [442] = 1,
    ACTIONS(168), 1,
      anon_sym_PERCENT_GT,
  [446] = 1,
    ACTIONS(170), 1,
      aux_sym_el_content_token3,
  [450] = 1,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
  [454] = 1,
    ACTIONS(174), 1,
      anon_sym_PERCENT_GT,
  [458] = 1,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
  [462] = 1,
    ACTIONS(178), 1,
      anon_sym_PERCENT_GT,
  [466] = 1,
    ACTIONS(180), 1,
      anon_sym_PERCENT_GT,
  [470] = 1,
    ACTIONS(182), 1,
      aux_sym_el_content_token4,
  [474] = 1,
    ACTIONS(184), 1,
      aux_sym_el_content_token3,
  [478] = 1,
    ACTIONS(186), 1,
      anon_sym_SQUOTE,
  [482] = 1,
    ACTIONS(188), 1,
      anon_sym_DASH_DASH_PERCENT_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 26,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 71,
  [SMALL_STATE(8)] = 90,
  [SMALL_STATE(9)] = 109,
  [SMALL_STATE(10)] = 128,
  [SMALL_STATE(11)] = 147,
  [SMALL_STATE(12)] = 166,
  [SMALL_STATE(13)] = 185,
  [SMALL_STATE(14)] = 204,
  [SMALL_STATE(15)] = 223,
  [SMALL_STATE(16)] = 242,
  [SMALL_STATE(17)] = 261,
  [SMALL_STATE(18)] = 280,
  [SMALL_STATE(19)] = 297,
  [SMALL_STATE(20)] = 311,
  [SMALL_STATE(21)] = 325,
  [SMALL_STATE(22)] = 339,
  [SMALL_STATE(23)] = 353,
  [SMALL_STATE(24)] = 367,
  [SMALL_STATE(25)] = 381,
  [SMALL_STATE(26)] = 392,
  [SMALL_STATE(27)] = 403,
  [SMALL_STATE(28)] = 414,
  [SMALL_STATE(29)] = 421,
  [SMALL_STATE(30)] = 428,
  [SMALL_STATE(31)] = 435,
  [SMALL_STATE(32)] = 442,
  [SMALL_STATE(33)] = 446,
  [SMALL_STATE(34)] = 450,
  [SMALL_STATE(35)] = 454,
  [SMALL_STATE(36)] = 458,
  [SMALL_STATE(37)] = 462,
  [SMALL_STATE(38)] = 466,
  [SMALL_STATE(39)] = 470,
  [SMALL_STATE(40)] = 474,
  [SMALL_STATE(41)] = 478,
  [SMALL_STATE(42)] = 482,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scriptlet, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scriptlet, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_el_expression, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_el_expression, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_el_expression, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_el_expression, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scriptlet, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scriptlet, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_el_content_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_el_content_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_el_content_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_el_content, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_attribute, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_attribute_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_attribute_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_el_content_repeat1, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_el_content_repeat1, 6, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [176] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__comment_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__comment_content] = sym__comment_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__comment_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_jsp_external_scanner_create(void);
void tree_sitter_jsp_external_scanner_destroy(void *);
bool tree_sitter_jsp_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_jsp_external_scanner_serialize(void *, char *);
void tree_sitter_jsp_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jsp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_jsp_external_scanner_create,
      tree_sitter_jsp_external_scanner_destroy,
      tree_sitter_jsp_external_scanner_scan,
      tree_sitter_jsp_external_scanner_serialize,
      tree_sitter_jsp_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "jsp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
